from __future__ import annotations

from typing import Protocol

from app.schemas.agent import AtlasAgentQueryRequest, AtlasAgentQueryResponse, AtlasAgentToolSpec
from app.schemas.alert import Alert
from app.schemas.asset import Asset
from app.schemas.frame import FrameEnvelope
from app.schemas.health import HealthResponse
from app.schemas.lead import Lead, LeadRefreshRequest, LeadRefreshResponse
from app.schemas.liquid_analyst import LiquidAnalystReport
from app.schemas.metrics import Metrics
from app.schemas.model_status import ModelStatus
from app.schemas.replay import ReplaySnapshot, ReplayStartRequest, ReplayState
from app.schemas.sam3_evidence import Sam3EvidenceReport


class AtlasService(Protocol):
    def get_health(self) -> HealthResponse: ...

    def get_model_status(self) -> ModelStatus: ...

    def list_assets(self) -> list[Asset]: ...

    def list_leads(self) -> list[Lead]: ...

    def refresh_leads(self, request: LeadRefreshRequest) -> LeadRefreshResponse: ...

    def list_agent_tools(self) -> list[AtlasAgentToolSpec]: ...

    def run_agent_query(self, request: AtlasAgentQueryRequest) -> AtlasAgentQueryResponse: ...

    def start_replay(self, request: ReplayStartRequest) -> ReplayState: ...

    def stop_replay(self) -> ReplayState: ...

    def get_replay_state(self) -> ReplayState: ...

    def get_replay_snapshot(self) -> ReplaySnapshot: ...

    def get_current_evidence(self) -> Sam3EvidenceReport: ...

    def get_asset_evidence(self, asset_id: str) -> Sam3EvidenceReport | None: ...

    def get_asset_analyst_report(self, asset_id: str) -> LiquidAnalystReport | None: ...

    def get_current_frame(self) -> FrameEnvelope: ...

    def get_baseline_frame(self) -> FrameEnvelope: ...

    def list_alerts(self) -> list[Alert]: ...

    def get_metrics(self) -> Metrics: ...
